version: '2'
services:
  postgres:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    command: ['postgres', '-c', 'log_statement=all']
    # restart: always
