export enum CountryCode {
  AF = 'AF',
  AX = 'AX',
  AL = 'AL',
  DZ = 'DZ',
  AS = 'AS',
  AD = 'AD',
  AO = 'AO',
  AI = 'AI',
  AQ = 'AQ',
  AG = 'AG',
  AR = 'AR',
  AM = 'AM',
  AW = 'AW',
  AU = 'AU',
  AT = 'AT',
  AZ = 'AZ',
  BS = 'BS',
  BH = 'BH',
  BD = 'BD',
  BB = 'BB',
  BY = 'BY',
  BE = 'BE',
  BZ = 'BZ',
  BJ = 'BJ',
  BM = 'BM',
  BT = 'BT',
  BO = 'BO',
  BQ = 'BQ',
  BA = 'BA',
  BW = 'BW',
  BV = 'BV',
  BR = 'BR',
  IO = 'IO',
  BN = 'BN',
  BG = 'BG',
  BF = 'BF',
  BI = 'BI',
  CV = 'CV',
  KH = 'KH',
  CM = 'CM',
  CA = 'CA',
  KY = 'KY',
  CF = 'CF',
  TD = 'TD',
  CL = 'CL',
  CN = 'CN',
  CX = 'CX',
  CC = 'CC',
  CO = 'CO',
  KM = 'KM',
  CG = 'CG',
  CD = 'CD',
  CK = 'CK',
  CR = 'CR',
  CI = 'CI',
  HR = 'HR',
  CU = 'CU',
  CW = 'CW',
  CY = 'CY',
  CZ = 'CZ',
  DK = 'DK',
  DJ = 'DJ',
  DM = 'DM',
  DO = 'DO',
  EC = 'EC',
  EG = 'EG',
  SV = 'SV',
  GQ = 'GQ',
  ER = 'ER',
  EE = 'EE',
  ET = 'ET',
  FK = 'FK',
  FO = 'FO',
  FJ = 'FJ',
  FI = 'FI',
  FR = 'FR',
  GF = 'GF',
  PF = 'PF',
  TF = 'TF',
  GA = 'GA',
  GM = 'GM',
  GE = 'GE',
  DE = 'DE',
  GH = 'GH',
  GI = 'GI',
  GR = 'GR',
  GL = 'GL',
  GD = 'GD',
  GP = 'GP',
  GU = 'GU',
  GT = 'GT',
  GG = 'GG',
  GN = 'GN',
  GW = 'GW',
  GY = 'GY',
  HT = 'HT',
  HM = 'HM',
  VA = 'VA',
  HN = 'HN',
  HK = 'HK',
  HU = 'HU',
  IS = 'IS',
  IN = 'IN',
  ID = 'ID',
  IR = 'IR',
  IQ = 'IQ',
  IE = 'IE',
  IM = 'IM',
  IL = 'IL',
  IT = 'IT',
  JM = 'JM',
  JP = 'JP',
  JE = 'JE',
  JO = 'JO',
  KZ = 'KZ',
  KE = 'KE',
  KI = 'KI',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KG = 'KG',
  LA = 'LA',
  LV = 'LV',
  LB = 'LB',
  LS = 'LS',
  LR = 'LR',
  LY = 'LY',
  LI = 'LI',
  LT = 'LT',
  LU = 'LU',
  MO = 'MO',
  MK = 'MK',
  MG = 'MG',
  MW = 'MW',
  MY = 'MY',
  MV = 'MV',
  ML = 'ML',
  MT = 'MT',
  MH = 'MH',
  MQ = 'MQ',
  MR = 'MR',
  MU = 'MU',
  YT = 'YT',
  MX = 'MX',
  FM = 'FM',
  MD = 'MD',
  MC = 'MC',
  MN = 'MN',
  ME = 'ME',
  MS = 'MS',
  MA = 'MA',
  MZ = 'MZ',
  MM = 'MM',
  NA = 'NA',
  NR = 'NR',
  NP = 'NP',
  NL = 'NL',
  NC = 'NC',
  NZ = 'NZ',
  NI = 'NI',
  NE = 'NE',
  NG = 'NG',
  NU = 'NU',
  NF = 'NF',
  MP = 'MP',
  NO = 'NO',
  OM = 'OM',
  PK = 'PK',
  PW = 'PW',
  PS = 'PS',
  PA = 'PA',
  PG = 'PG',
  PY = 'PY',
  PE = 'PE',
  PH = 'PH',
  PN = 'PN',
  PL = 'PL',
  PT = 'PT',
  PR = 'PR',
  QA = 'QA',
  RE = 'RE',
  RO = 'RO',
  RU = 'RU',
  RW = 'RW',
  BL = 'BL',
  SH = 'SH',
  KN = 'KN',
  LC = 'LC',
  MF = 'MF',
  PM = 'PM',
  VC = 'VC',
  WS = 'WS',
  SM = 'SM',
  ST = 'ST',
  SA = 'SA',
  SN = 'SN',
  RS = 'RS',
  SC = 'SC',
  SL = 'SL',
  SG = 'SG',
  SX = 'SX',
  SK = 'SK',
  SI = 'SI',
  SB = 'SB',
  SO = 'SO',
  ZA = 'ZA',
  GS = 'GS',
  SS = 'SS',
  ES = 'ES',
  LK = 'LK',
  SD = 'SD',
  SR = 'SR',
  SJ = 'SJ',
  SZ = 'SZ',
  SE = 'SE',
  CH = 'CH',
  SY = 'SY',
  TW = 'TW',
  TJ = 'TJ',
  TZ = 'TZ',
  TH = 'TH',
  TL = 'TL',
  TG = 'TG',
  TK = 'TK',
  TO = 'TO',
  TT = 'TT',
  TN = 'TN',
  TR = 'TR',
  TM = 'TM',
  TC = 'TC',
  TV = 'TV',
  UG = 'UG',
  UA = 'UA',
  AE = 'AE',
  GB = 'GB',
  US = 'US',
  UM = 'UM',
  UY = 'UY',
  UZ = 'UZ',
  VU = 'VU',
  VE = 'VE',
  VN = 'VN',
  VG = 'VG',
  VI = 'VI',
  WF = 'WF',
  EH = 'EH',
  YE = 'YE',
  ZM = 'ZM',
  ZW = 'ZW',
}

interface CountryConfig {
  enabled: boolean;
}

export const COUNTRY_LIST: {
  [key in CountryCode]: CountryConfig;
} = {
  [CountryCode.AF]: { enabled: true },
  [CountryCode.AX]: { enabled: true },
  [CountryCode.AL]: { enabled: true },
  [CountryCode.DZ]: { enabled: true },
  [CountryCode.AS]: { enabled: true },
  [CountryCode.AD]: { enabled: true },
  [CountryCode.AO]: { enabled: true },
  [CountryCode.AI]: { enabled: true },
  [CountryCode.AQ]: { enabled: true },
  [CountryCode.AG]: { enabled: true },
  [CountryCode.AR]: { enabled: true },
  [CountryCode.AM]: { enabled: true },
  [CountryCode.AW]: { enabled: true },
  [CountryCode.AU]: { enabled: true },
  [CountryCode.AT]: { enabled: true },
  [CountryCode.AZ]: { enabled: true },
  [CountryCode.BS]: { enabled: true },
  [CountryCode.BH]: { enabled: true },
  [CountryCode.BD]: { enabled: true },
  [CountryCode.BB]: { enabled: true },
  [CountryCode.BY]: { enabled: true },
  [CountryCode.BE]: { enabled: true },
  [CountryCode.BZ]: { enabled: true },
  [CountryCode.BJ]: { enabled: true },
  [CountryCode.BM]: { enabled: true },
  [CountryCode.BT]: { enabled: true },
  [CountryCode.BO]: { enabled: true },
  [CountryCode.BQ]: { enabled: true },
  [CountryCode.BA]: { enabled: true },
  [CountryCode.BW]: { enabled: true },
  [CountryCode.BV]: { enabled: true },
  [CountryCode.BR]: { enabled: true },
  [CountryCode.IO]: { enabled: true },
  [CountryCode.BN]: { enabled: true },
  [CountryCode.BG]: { enabled: true },
  [CountryCode.BF]: { enabled: true },
  [CountryCode.BI]: { enabled: true },
  [CountryCode.CV]: { enabled: true },
  [CountryCode.KH]: { enabled: true },
  [CountryCode.CM]: { enabled: true },
  [CountryCode.CA]: { enabled: true },
  [CountryCode.KY]: { enabled: true },
  [CountryCode.CF]: { enabled: true },
  [CountryCode.TD]: { enabled: true },
  [CountryCode.CL]: { enabled: true },
  [CountryCode.CN]: { enabled: true },
  [CountryCode.CX]: { enabled: true },
  [CountryCode.CC]: { enabled: true },
  [CountryCode.CO]: { enabled: true },
  [CountryCode.KM]: { enabled: true },
  [CountryCode.CG]: { enabled: true },
  [CountryCode.CD]: { enabled: true },
  [CountryCode.CK]: { enabled: true },
  [CountryCode.CR]: { enabled: true },
  [CountryCode.CI]: { enabled: true },
  [CountryCode.HR]: { enabled: true },
  [CountryCode.CU]: { enabled: true },
  [CountryCode.CW]: { enabled: true },
  [CountryCode.CY]: { enabled: true },
  [CountryCode.CZ]: { enabled: true },
  [CountryCode.DK]: { enabled: true },
  [CountryCode.DJ]: { enabled: true },
  [CountryCode.DM]: { enabled: true },
  [CountryCode.DO]: { enabled: true },
  [CountryCode.EC]: { enabled: true },
  [CountryCode.EG]: { enabled: true },
  [CountryCode.SV]: { enabled: true },
  [CountryCode.GQ]: { enabled: true },
  [CountryCode.ER]: { enabled: true },
  [CountryCode.EE]: { enabled: true },
  [CountryCode.ET]: { enabled: true },
  [CountryCode.FK]: { enabled: true },
  [CountryCode.FO]: { enabled: true },
  [CountryCode.FJ]: { enabled: true },
  [CountryCode.FI]: { enabled: true },
  [CountryCode.FR]: { enabled: true },
  [CountryCode.GF]: { enabled: true },
  [CountryCode.PF]: { enabled: true },
  [CountryCode.TF]: { enabled: true },
  [CountryCode.GA]: { enabled: true },
  [CountryCode.GM]: { enabled: true },
  [CountryCode.GE]: { enabled: true },
  [CountryCode.DE]: { enabled: true },
  [CountryCode.GH]: { enabled: true },
  [CountryCode.GI]: { enabled: true },
  [CountryCode.GR]: { enabled: true },
  [CountryCode.GL]: { enabled: true },
  [CountryCode.GD]: { enabled: true },
  [CountryCode.GP]: { enabled: true },
  [CountryCode.GU]: { enabled: true },
  [CountryCode.GT]: { enabled: true },
  [CountryCode.GG]: { enabled: true },
  [CountryCode.GN]: { enabled: true },
  [CountryCode.GW]: { enabled: true },
  [CountryCode.GY]: { enabled: true },
  [CountryCode.HT]: { enabled: true },
  [CountryCode.HM]: { enabled: true },
  [CountryCode.VA]: { enabled: true },
  [CountryCode.HN]: { enabled: true },
  [CountryCode.HK]: { enabled: true },
  [CountryCode.HU]: { enabled: true },
  [CountryCode.IS]: { enabled: true },
  [CountryCode.IN]: { enabled: true },
  [CountryCode.ID]: { enabled: true },
  [CountryCode.IR]: { enabled: true },
  [CountryCode.IQ]: { enabled: true },
  [CountryCode.IE]: { enabled: true },
  [CountryCode.IM]: { enabled: true },
  [CountryCode.IL]: { enabled: true },
  [CountryCode.IT]: { enabled: true },
  [CountryCode.JM]: { enabled: true },
  [CountryCode.JP]: { enabled: true },
  [CountryCode.JE]: { enabled: true },
  [CountryCode.JO]: { enabled: true },
  [CountryCode.KZ]: { enabled: true },
  [CountryCode.KE]: { enabled: true },
  [CountryCode.KI]: { enabled: true },
  [CountryCode.KP]: { enabled: true },
  [CountryCode.KR]: { enabled: true },
  [CountryCode.KW]: { enabled: true },
  [CountryCode.KG]: { enabled: true },
  [CountryCode.LA]: { enabled: true },
  [CountryCode.LV]: { enabled: true },
  [CountryCode.LB]: { enabled: true },
  [CountryCode.LS]: { enabled: true },
  [CountryCode.LR]: { enabled: true },
  [CountryCode.LY]: { enabled: true },
  [CountryCode.LI]: { enabled: true },
  [CountryCode.LT]: { enabled: true },
  [CountryCode.LU]: { enabled: true },
  [CountryCode.MO]: { enabled: true },
  [CountryCode.MK]: { enabled: true },
  [CountryCode.MG]: { enabled: true },
  [CountryCode.MW]: { enabled: true },
  [CountryCode.MY]: { enabled: true },
  [CountryCode.MV]: { enabled: true },
  [CountryCode.ML]: { enabled: true },
  [CountryCode.MT]: { enabled: true },
  [CountryCode.MH]: { enabled: true },
  [CountryCode.MQ]: { enabled: true },
  [CountryCode.MR]: { enabled: true },
  [CountryCode.MU]: { enabled: true },
  [CountryCode.YT]: { enabled: true },
  [CountryCode.MX]: { enabled: true },
  [CountryCode.FM]: { enabled: true },
  [CountryCode.MD]: { enabled: true },
  [CountryCode.MC]: { enabled: true },
  [CountryCode.MN]: { enabled: true },
  [CountryCode.ME]: { enabled: true },
  [CountryCode.MS]: { enabled: true },
  [CountryCode.MA]: { enabled: true },
  [CountryCode.MZ]: { enabled: true },
  [CountryCode.MM]: { enabled: true },
  [CountryCode.NA]: { enabled: true },
  [CountryCode.NR]: { enabled: true },
  [CountryCode.NP]: { enabled: true },
  [CountryCode.NL]: { enabled: true },
  [CountryCode.NC]: { enabled: true },
  [CountryCode.NZ]: { enabled: true },
  [CountryCode.NI]: { enabled: true },
  [CountryCode.NE]: { enabled: true },
  [CountryCode.NG]: { enabled: true },
  [CountryCode.NU]: { enabled: true },
  [CountryCode.NF]: { enabled: true },
  [CountryCode.MP]: { enabled: true },
  [CountryCode.NO]: { enabled: true },
  [CountryCode.OM]: { enabled: true },
  [CountryCode.PK]: { enabled: true },
  [CountryCode.PW]: { enabled: true },
  [CountryCode.PS]: { enabled: true },
  [CountryCode.PA]: { enabled: true },
  [CountryCode.PG]: { enabled: true },
  [CountryCode.PY]: { enabled: true },
  [CountryCode.PE]: { enabled: true },
  [CountryCode.PH]: { enabled: true },
  [CountryCode.PN]: { enabled: true },
  [CountryCode.PL]: { enabled: true },
  [CountryCode.PT]: { enabled: true },
  [CountryCode.PR]: { enabled: true },
  [CountryCode.QA]: { enabled: true },
  [CountryCode.RE]: { enabled: true },
  [CountryCode.RO]: { enabled: true },
  [CountryCode.RU]: { enabled: true },
  [CountryCode.RW]: { enabled: true },
  [CountryCode.BL]: { enabled: true },
  [CountryCode.SH]: { enabled: true },
  [CountryCode.KN]: { enabled: true },
  [CountryCode.LC]: { enabled: true },
  [CountryCode.MF]: { enabled: true },
  [CountryCode.PM]: { enabled: true },
  [CountryCode.VC]: { enabled: true },
  [CountryCode.WS]: { enabled: true },
  [CountryCode.SM]: { enabled: true },
  [CountryCode.ST]: { enabled: true },
  [CountryCode.SA]: { enabled: true },
  [CountryCode.SN]: { enabled: true },
  [CountryCode.RS]: { enabled: true },
  [CountryCode.SC]: { enabled: true },
  [CountryCode.SL]: { enabled: true },
  [CountryCode.SG]: { enabled: true },
  [CountryCode.SX]: { enabled: true },
  [CountryCode.SK]: { enabled: true },
  [CountryCode.SI]: { enabled: true },
  [CountryCode.SB]: { enabled: true },
  [CountryCode.SO]: { enabled: true },
  [CountryCode.ZA]: { enabled: true },
  [CountryCode.GS]: { enabled: true },
  [CountryCode.SS]: { enabled: true },
  [CountryCode.ES]: { enabled: true },
  [CountryCode.LK]: { enabled: true },
  [CountryCode.SD]: { enabled: true },
  [CountryCode.SR]: { enabled: true },
  [CountryCode.SJ]: { enabled: true },
  [CountryCode.SZ]: { enabled: true },
  [CountryCode.SE]: { enabled: true },
  [CountryCode.CH]: { enabled: true },
  [CountryCode.SY]: { enabled: true },
  [CountryCode.TW]: { enabled: true },
  [CountryCode.TJ]: { enabled: true },
  [CountryCode.TZ]: { enabled: true },
  [CountryCode.TH]: { enabled: true },
  [CountryCode.TL]: { enabled: true },
  [CountryCode.TG]: { enabled: true },
  [CountryCode.TK]: { enabled: true },
  [CountryCode.TO]: { enabled: true },
  [CountryCode.TT]: { enabled: true },
  [CountryCode.TN]: { enabled: true },
  [CountryCode.TR]: { enabled: true },
  [CountryCode.TM]: { enabled: true },
  [CountryCode.TC]: { enabled: true },
  [CountryCode.TV]: { enabled: true },
  [CountryCode.UG]: { enabled: true },
  [CountryCode.UA]: { enabled: true },
  [CountryCode.AE]: { enabled: true },
  [CountryCode.GB]: { enabled: true },
  [CountryCode.US]: { enabled: true },
  [CountryCode.UM]: { enabled: true },
  [CountryCode.UY]: { enabled: true },
  [CountryCode.UZ]: { enabled: true },
  [CountryCode.VU]: { enabled: true },
  [CountryCode.VE]: { enabled: true },
  [CountryCode.VN]: { enabled: true },
  [CountryCode.VG]: { enabled: true },
  [CountryCode.VI]: { enabled: true },
  [CountryCode.WF]: { enabled: true },
  [CountryCode.EH]: { enabled: true },
  [CountryCode.YE]: { enabled: true },
  [CountryCode.ZM]: { enabled: true },
  [CountryCode.ZW]: { enabled: true },
} as const;
